### ISSUE TITLE
chan send & crash, unable to reproduce in consistent manner

### ISSUE THREAD

**Issue by arnos** [graph-gophers/graphql-go#100]
We've have a weird crash that happens once in a blue moon, we just see a bunch of [chan send] log outputs and nothing else to indicate what happened.

I'm unable to reproduce it myself and haven't been able to narrow it down.

I'll be spending some time over the next weeks to narrow it down.

In the mean time I was wondering if someone else has seen something similar and/or might have an idea what is causing this

The following is logged repeatably (20-30 times) the only thing changing is the goroutine number
```
[...] 
goroutine 855 [chan send]:
github.com/neelance/graphql-go/internal/exec.execFieldSelection(0x1e05100, 0xc420104000, 0xc4201861e0, 0xc420348480, 0xc420104001)
    /Users/kurtisfunai/Code/go/src/github.com/neelance/graphql-go/internal/exec/exec.go:152 +0x348
github.com/neelance/graphql-go/internal/exec.(*Request).execSelections.func1(0xc42017a4d0, 0xc4201861e0, 0x1e05100, 0xc420104000, 0xc420348480)
    /Users/kurtisfunai/Code/go/src/github.com/neelance/graphql-go/internal/exec/exec.go:79 +0xdf
created by github.com/neelance/graphql-go/internal/exec.(*Request).execSelections
    /Users/kurtisfunai/Code/go/src/github.com/neelance/graphql-go/internal/exec/exec.go:80 +0x424
```

**Comment by neelance** [comment]
Have you tried running with the race detector enabled?

**Comment by arnos** [comment]
No I was focused on reproducing the issue, I'll have the guys run the API
instance with race detector turned on and see if we get more out of it

On Jul 4, 2017 1:33 PM, "Richard Musiol" <notifications@github.com> wrote:

Have you tried running with the race detector enabled?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neelance/graphql-go/issues/100#issuecomment-312924108>,
or mute the thread
