### ISSUE TITLE
Can't traverse from implementing type to interface in fragment

### ISSUE THREAD

**Issue by caseymrm** [graph-gophers/graphql-go#113]
Hello, ran into a minor problem where if you have a fragment on a type that implements an interface, you can't them embed an inline fragment that goes back to the interface.

Here's an example of it working on the public graphiql server (in their schema, all objects implement the Node interface, so easy to make a quick test): [example working query](http://graphql.org/swapi-graphql/?query=query%20Test%20%7B%0A%20%20allPlanets%20%7B%0A%20%20%20%20planets%20%7B%0A%20%20%20%20%20%20...%20on%20Planet%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20...%20on%20Node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=Test)

Here's a test case illustrating the bug by going down into Droid, then back up to Character:

```
func TestInterfaceTraverse(t *testing.T) {
        gqltesting.RunTests(t, []*gqltesting.Test{
                {
                        Schema: starwarsSchema,
                        Query: `
                                query HeroForEpisode($episode: Episode!) {
                                        hero(episode: $episode) {
                                                name
                                                ... on Droid {
                                                        primaryFunction
                                                        ... on Character {
                                                              id
                                                        }
                                                }
                                                ... on Human {
                                                        height
                                                }
                                        }
                                }
                        `,
                        Variables: map[string]interface{}{
                                "episode": "JEDI",
                        },
                        ExpectedResult: `
                                {
                                        "hero": {
                                                "id": "2001",
                                                "name": "R2-D2",
                                                "primaryFunction": "Astromech"
                                        }
                                }
                        `,
                },
        })
}
```

Currently this prints the following:
```
$ go test graphql_test.go
2017/09/26 15:20:50 graphql: panic occurred: {{"Character" {'\a' '@'}}} does not implement "Droid"
goroutine 40 [running]:
github.com/neelance/graphql-go/log.(*DefaultLogger).LogPanic(0x159d130, 0x1548000, 0xc42021b470, 0x1331ee0, 0xc420213020)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/log/log.go:21 +0x77
github.com/neelance/graphql-go/internal/exec.(*Request).handlePanic(0xc420214ba0, 0x1548000, 0xc42021b470)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/exec.go:34 +0x87
panic(0x1331ee0, 0xc420213020)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/neelance/graphql-go/internal/exec/selected.applyFragment(0xc420214ba0, 0xc4201da500, 0xc420214ae0, 0x0, 0x0, 0xc420213000)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:170 +0x3ff
github.com/neelance/graphql-go/internal/exec/selected.applySelectionSet(0xc420214ba0, 0xc4201da500, 0xc420211340, 0x2, 0x2, 0xc420287501, 0x0, 0x0)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:150 +0x17dd
github.com/neelance/graphql-go/internal/exec/selected.applyFragment(0xc420214ba0, 0xc4201da520, 0xc420214a80, 0x0, 0x0, 0xc420212ff0)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:175 +0xf4
github.com/neelance/graphql-go/internal/exec/selected.applySelectionSet(0xc420214ba0, 0xc4201da520, 0xc42020a7c0, 0x3, 0x4, 0x131a720, 0x13e1250, 0xc42016e960)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:150 +0x17dd
github.com/neelance/graphql-go/internal/exec/selected.applyField(0xc420214ba0, 0x1542ec0, 0xc4201da520, 0xc42020a7c0, 0x3, 0x4, 0x0, 0x0, 0x80000000000)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:184 +0x16d
github.com/neelance/graphql-go/internal/exec/selected.applySelectionSet(0xc420214ba0, 0xc4201dafa0, 0xc420212f20, 0x1, 0x1, 0xc420287b58, 0xc420287b60, 0x0)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:134 +0x4dc
github.com/neelance/graphql-go/internal/exec/selected.ApplyOperation(0xc420214ba0, 0xc4201628c0, 0xc42022e240, 0x1548000, 0xc42021b470, 0x154a800)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/selected/selected.go:39 +0x95
github.com/neelance/graphql-go/internal/exec.(*Request).Execute.func1(0xc420214ba0, 0x1548000, 0xc42021b470, 0xc4201628c0, 0xc42022e240, 0xc42020e3f0)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/exec.go:47 +0x8c
github.com/neelance/graphql-go/internal/exec.(*Request).Execute(0xc420214ba0, 0x1548000, 0xc42021b470, 0xc4201628c0, 0xc42022e240, 0x0, 0x0, 0xc42021b2c0, 0xc42021b440, 0x1548000, ...)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/internal/exec/exec.go:49 +0x7c
github.com/neelance/graphql-go.(*Schema).exec(0xc420061280, 0x1547f80, 0xc4200160d8, 0x13b00c0, 0x18f, 0x0, 0x0, 0xc42021b2c0, 0xc4201628c0, 0xc4203566b0)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/graphql.go:170 +0x84d
github.com/neelance/graphql-go.(*Schema).Exec(0xc420061280, 0x1547f80, 0xc4200160d8, 0x13b00c0, 0x18f, 0x0, 0x0, 0xc42021b2c0, 0x110)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/graphql.go:132 +0x8f
github.com/neelance/graphql-go/gqltesting.RunTest(0xc4202261e0, 0xc42020a780)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/gqltesting/testing.go:38 +0x88
github.com/neelance/graphql-go/gqltesting.RunTests(0xc4202261e0, 0xc420216140, 0x1, 0x1)
	/Users/casey/gocode/src/github.com/neelance/graphql-go/gqltesting/testing.go:25 +0x181
command-line-arguments_test.TestInterfaceTraverse(0xc4202261e0)
	/Users/casey/code/graphql-go/graphql_test.go:1749 +0x189
testing.tRunner(0xc4202261e0, 0x13b8788)
	/usr/local/opt/go/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:789 +0x2de
--- FAIL: TestInterfaceTraverse (0.00s)
	testing.go:40: graphql: graphql: panic occurred: {{"Character" {'\a' '@'}}} does not implement "Droid"
FAIL
FAIL	command-line-arguments	0.020s
```

If anybody else is hitting this, for now I just have each interface have a "self" field that returns the interface (for example ```self: Character!``` here), so you could do the following:
```
query HeroForEpisode($episode: Episode!) {
        hero(episode: $episode) {
                name
                ... on Droid {
                        primaryFunction
                        self {
                              ... on Character {
                                    id
                              }
                        }
                }
                ... on Human {
                        height
                }
        }
}
```

But thought it'd be good to submit a bug. Let me know if I'm doing something wrong, thanks!

**Comment by pavelnikolov** [comment]
@mjm, @caseymrm is this allowed in the spec?

**Comment by mjm** [comment]
As best as I can tell, it is allowed. See [this section](https://spec.graphql.org/October2021/#sec-Fragment-spread-is-possible) that basically boils down to "a fragment spread is allowed as long as there's some type that could actually match it." Otherwise, I see nothing that forbids this sort of thing, and as mentioned in the issue, it works in the official graphql server.

**Comment by caseymrm** [comment]
Thank you!

**Comment by pavelnikolov** [comment]
No, thank you for the patience on this one! I'll release it with `v1.6.0` expected in March.
