### ISSUE TITLE
bad union syntax = parser non-termination

### ISSUE THREAD

**Issue by brandonbloom** [graph-gophers/graphql-go#491]
there is an infinite loop in the parser. here's a reproduction:

```
package main

import "github.com/graph-gophers/graphql-go"

func main() {
	graphql.MustParseSchema(`type U = T`, nil)
}
```

There is a typo here: `type U = T` should have been `union U = T`, but this loops infinitely instead of reporting a syntax error.

**Comment by brandonbloom** [comment]
stack trace uncovers the bug:

```
$ go run .
^\SIGQUIT: quit
PC=0x116d5e6 m=0 sigcode=0

goroutine 1 [running]:
github.com/graph-gophers/graphql-go/internal/schema.parseObjectDef(0xc00008a680)
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/internal/schema/schema.go:379 +0xa6 fp=0xc0000adab0 sp=0xc0000ada38 pc=0x116d5e6
github.com/graph-gophers/graphql-go/internal/schema.parseSchema(0xc0000c8750, 0xc00008a680)
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/internal/schema/schema.go:323 +0xb3 fp=0xc0000adbb0 sp=0xc0000adab0 pc=0x116cb93
github.com/graph-gophers/graphql-go/internal/schema.Parse.func1()
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/internal/schema/schema.go:31 +0x25 fp=0xc0000adbd0 sp=0xc0000adbb0 pc=0x116ae45
github.com/graph-gophers/graphql-go/internal/common.(*Lexer).CatchSyntaxError(0x11baa28, 0xa)
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/internal/common/lexer.go:52 +0x73 fp=0xc0000adc10 sp=0xc0000adbd0 pc=0x10d5893
github.com/graph-gophers/graphql-go/internal/schema.Parse(0xc0000c8750, {0x11baa28, 0x13625a8}, 0xa0)
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/internal/schema/schema.go:31 +0x8f fp=0xc0000adee8 sp=0xc0000adc10 pc=0x1169f0f
github.com/graph-gophers/graphql-go.ParseSchema({0x11baa28, 0xa}, {0x0, 0x0}, {0x0, 0x0, 0xc0000001a0})
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/graphql.go:46 +0x18d fp=0xc0000adf38 sp=0xc0000adee8 pc=0x116ee6d
github.com/graph-gophers/graphql-go.MustParseSchema(...)
	/Users/brandonbloom/Projects/go/pkg/mod/github.com/graph-gophers/graphql-go@v1.2.0/graphql.go:64
main.main()
	/tmp/blah/blah.go:6 +0x31 fp=0xc0000adf80 sp=0xc0000adf38 pc=0x116f351
runtime.main()
	/usr/local/Cellar/go/1.17.3/libexec/src/runtime/proc.go:255 +0x227 fp=0xc0000adfe0 sp=0xc0000adf80 pc=0x10360e7
runtime.goexit()
	/usr/local/Cellar/go/1.17.3/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000adfe8 sp=0xc0000adfe0 pc=0x1062861

rax    0xc0000c8ea0
rbx    0x1640108
rcx    0x1
rdx    0xc00008a680
rdi    0x0
rsi    0x3d
rbp    0xc0000adaa0
rsp    0xc0000ada38
r8     0x90
r9     0x70
r10    0x14
r11    0x11f73a8
r12    0x203000
r13    0x203000
r14    0xc0000001a0
r15    0x5106479
rip    0x116d5e6
rflags 0x283
cs     0x2b
fs     0x0
gs     0x0
exit status 2
```

Looks like the loop in parseObjectDef needs a fallback case that does `l.SyntaxError(fmt.Sprintf(`unexpected ...`

**Comment by cnnrrss** [comment]
Hey, first time contributor 👋 . I'd like to give this one a go if nobody has picked it up yet.

**Comment by pavelnikolov** [comment]
@cnnrrss contributions are more than welcome

**Comment by DallasP9124** [comment]
@pavelnikolov is this still an issue with the those PR's in?

**Comment by pavelnikolov** [comment]
@DallasP9124 This issue should be closed. The first PR fixed it.
